services:
  # MySQL数据库服务
  mysql:
    image: mysql:8.0
    container_name: dcc_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-sfw3470699}
      MYSQL_DATABASE: ${DB_NAME:-dcc_employee_db}
      MYSQL_USER: ${DB_USER:-dcc_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-sfw3470699}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database:/docker-entrypoint-initdb.d
    networks:
      - dcc_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # 后端API服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: dcc_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # 环境配置
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - DEBUG=${DEBUG:-False}
      
      # 数据库配置
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=${DB_USER:-dcc_user}
      - DB_PASSWORD=${DB_PASSWORD:-sfw3470699}
      - DB_NAME=${DB_NAME:-dcc_employee_db}
      
      # JWT配置
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-dcc-jwt-secret-key-2024}
      - JWT_EXPIRE_HOURS=${JWT_EXPIRE_HOURS:-24}
      
      # 阿里云配置
      - ALIBABA_CLOUD_ACCESS_KEY_ID=${ALIBABA_CLOUD_ACCESS_KEY_ID}
      - ALIBABA_CLOUD_ACCESS_KEY_SECRET=${ALIBABA_CLOUD_ACCESS_KEY_SECRET}
      - INSTANCE_ID=${INSTANCE_ID}
      
      # 阿里百炼配置
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
      - ALIBAILIAN_APP_ID=${ALIBAILIAN_APP_ID}
      
      # 外部API配置
      - SCENE_ID_API_URL=${SCENE_ID_API_URL:-https://your-external-api.com/get-scene-id}
      - API_TIMEOUT=${API_TIMEOUT:-30}
      - EXTERNAL_API_TOKEN=${EXTERNAL_API_TOKEN}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - dcc_network
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 前端服务
  frontend:
    build: ./dcc-digital-employee
    container_name: dcc_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - dcc_network

volumes:
  mysql_data:

networks:
  dcc_network:
    driver: bridge