# 快速构建版Docker Compose配置
# 使用预构建镜像和优化设置

services:
  # MySQL数据库 - 使用预构建镜像
  mysql:
    image: mysql:8.0
    container_name: dcc-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: dcc_employee_db
      MYSQL_USER: dcc_user
      MYSQL_PASSWORD: ",Dcc123456"
      TZ: Asia/Shanghai
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database:/docker-entrypoint-initdb.d:ro
    networks:
      - dcc-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123456"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 后端服务 - 使用快速构建
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.fast
    container_name: dcc-backend
    restart: always
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: dcc_user
      DB_PASSWORD: ",Dcc123456"
      DB_NAME: dcc_employee_db
      JWT_SECRET_KEY: dcc-jwt-secret-key-2024
      JWT_EXPIRE_HOURS: 24
      ENVIRONMENT: production
      DEBUG: "False"
      ALIBABA_CLOUD_ACCESS_KEY_ID: ${ALIBABA_CLOUD_ACCESS_KEY_ID:-}
      ALIBABA_CLOUD_ACCESS_KEY_SECRET: ${ALIBABA_CLOUD_ACCESS_KEY_SECRET:-}
      INSTANCE_ID: ${INSTANCE_ID:-}
      DASHSCOPE_API_KEY: ${DASHSCOPE_API_KEY:-}
      ALIBAILIAN_APP_ID: ${ALIBAILIAN_APP_ID:-}
    ports:
      - "8001:8000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - dcc-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 前端服务 - 使用预构建Node.js镜像
  frontend:
    image: node:18-alpine
    container_name: dcc-frontend
    restart: always
    working_dir: /app
    environment:
      NODE_ENV: production
      DOCKER_ENV: "true"
      NEXT_PUBLIC_API_BASE_URL: http://campus.kongbaijiyi.com/api
    ports:
      - "3001:3000"
    volumes:
      - ./dcc-digital-employee:/app
      - /app/node_modules
      - /app/.next
    command: >
      sh -c "
        npm install --registry=https://registry.npmmirror.com &&
        npm run build &&
        npm start
      "
    depends_on:
      - backend
    networks:
      - dcc-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: dcc-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-docker.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - dcc-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  dcc-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  nginx_logs:
    driver: local
